services:
  textchecker:
    build:
      context: .
    container_name: textchecker-cont
    env_file:
      - path: ./ai.env
        required: true
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2gb
